const state = { images: [], selected: null, filter: 'all', user: null };
const $ = (s) => document.querySelector(s);
const imageKey = 'chilltheme-images-v1';
const userKey = 'chilltheme-user-v1';
const esc = (value) => String(value).replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));

function load() { try { state.images = JSON.parse(localStorage.getItem(imageKey) || '[]'); state.user = JSON.parse(localStorage.getItem(userKey) || 'null'); } catch { state.images = []; } }
function save() { localStorage.setItem(imageKey, JSON.stringify(state.images)); updateStats(); }
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(window.__toast); window.__toast = setTimeout(() => el.classList.remove('show'), 3000); }
function updateStats() { $('#countText').textContent = state.images.length; $('#storageText').textContent = `${state.images.length} ảnh`; $('#storageBar').style.width = `${Math.min(100, state.images.length * 8)}%`; $('#greeting').textContent = state.user ? `KHO HÌNH CỦA ${state.user.email.split('@')[0].toUpperCase()}` : 'YOUR VISUAL ARCHIVE'; }
function showView(view) { const logged = Boolean(state.user); $('#authView').classList.toggle('hidden', logged); $('#libraryView').classList.toggle('hidden', !logged || view !== 'library'); $('#settingsView').classList.toggle('hidden', !logged || view !== 'settings'); $('#pageTitle').textContent = view === 'settings' ? 'Thiết bị & tài khoản' : 'Không gian của bạn'; document.querySelectorAll('.nav-item').forEach((n) => n.classList.toggle('active', n.dataset.view === view)); renderGallery(); }
function renderGallery() { const gallery = $('#gallery'); const empty = $('#emptyState'); if (!state.user) return; const filtered = state.images.filter((image) => state.filter === 'all' || image.kind === state.filter); gallery.innerHTML = filtered.map((image, index) => `<article class="wallpaper-card" data-id="${image.id}" style="animation-delay:${index * 45}ms"><img src="${image.dataUrl}" alt="${esc(image.name)}">${image.kind === 'gif' ? '<span class="gif-badge">GIF / LIVE</span>' : ''}<div class="card-overlay"><div><strong>${esc(image.name)}</strong><small>${image.kind === 'gif' ? 'ẢNH ĐỘNG' : 'ẢNH TĨNH'}</small></div><span>↗</span></div></article>`).join(''); empty.classList.toggle('hidden', filtered.length > 0); gallery.classList.toggle('hidden', filtered.length === 0); document.querySelectorAll('.wallpaper-card').forEach((card) => card.addEventListener('click', () => openDetail(card.dataset.id))); updateStats(); }
function openDetail(id) { const image = state.images.find((item) => item.id === id); if (!image) return; state.selected = image; $('#detailMedia').innerHTML = `<img src="${image.dataUrl}" alt="${esc(image.name)}">`; $('#detailName').textContent = image.name; $('#detailType').textContent = image.kind === 'gif' ? 'GIF / LIVE WALLPAPER' : 'STATIC WALLPAPER'; $('#detailMeta').textContent = `${formatBytes(image.size)} · ${new Date(image.createdAt).toLocaleDateString('vi-VN')}`; $('#detailDialog').showModal(); }
function formatBytes(bytes) { if (!bytes) return 'Kích thước không xác định'; return `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
function readFile(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
async function addFiles(files) { const list = Array.from(files); for (const file of list) { if (!file.type.startsWith('image/')) continue; try { state.images.unshift({ id: crypto.randomUUID(), name: file.name, size: file.size, type: file.type, kind: file.type === 'image/gif' ? 'gif' : 'static', dataUrl: await readFile(file), createdAt: Date.now() }); } catch { toast('Không thể đọc một ảnh.'); } } save(); renderGallery(); toast(list.length > 1 ? `Đã thêm ${list.length} ảnh vào thư viện.` : 'Đã thêm ảnh vào thư viện.'); }

$('#authForm').addEventListener('submit', (event) => { event.preventDefault(); state.user = { email: $('#email').value.trim() }; localStorage.setItem(userKey, JSON.stringify(state.user)); $('#userName').textContent = state.user.email.split('@')[0]; $('#settingsEmail').textContent = state.user.email; showView('library'); toast('Chào mừng bạn đến với ChillTheme.'); });
$('#uploadBtn').addEventListener('click', () => $('#fileInput').click()); $('#emptyUpload').addEventListener('click', () => $('#fileInput').click()); $('#fileInput').addEventListener('change', (e) => addFiles(e.target.files));
$('#closeDialog').addEventListener('click', () => $('#detailDialog').close());
$('#deleteBtn').addEventListener('click', () => { if (!state.selected) return; state.images = state.images.filter((image) => image.id !== state.selected.id); save(); $('#detailDialog').close(); renderGallery(); toast('Đã xóa ảnh khỏi thư viện.'); });
$('#wallpaperBtn').addEventListener('click', async () => { if (!state.selected) return; const button = $('#wallpaperBtn'); button.disabled = true; button.textContent = 'Đang xử lý…'; const result = window.chilltheme ? await window.chilltheme.setWallpaper({ dataUrl: state.selected.dataUrl, kind: state.selected.kind }) : { ok: false, message: 'Hãy chạy app bằng Electron để đặt hình nền.' }; button.disabled = false; button.textContent = '✦ Đặt làm hình nền'; toast(result.message); });
document.querySelectorAll('.chip').forEach((chip) => chip.addEventListener('click', () => { state.filter = chip.dataset.filter; document.querySelectorAll('.chip').forEach((c) => c.classList.toggle('active', c === chip)); renderGallery(); }));
document.querySelectorAll('.nav-item').forEach((item) => item.addEventListener('click', () => showView(item.dataset.view)));
$('#logoutBtn').addEventListener('click', () => { state.user = null; localStorage.removeItem(userKey); showView('library'); toast('Đã đăng xuất khỏi thiết bị.'); });
$('#searchBtn').addEventListener('click', () => toast('Tìm kiếm nâng cao sẽ có trong bản tiếp theo.'));
load(); if (state.user) { $('#userName').textContent = state.user.email.split('@')[0]; $('#settingsEmail').textContent = state.user.email; } showView('library');
