const state = { images: [], selected: null, filter: 'all' };
const $ = (s) => document.querySelector(s);
const imageKey = 'chilltheme-images-v1';
const esc = (value) => String(value).replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[c]));

function load() { try { state.images = JSON.parse(localStorage.getItem(imageKey) || '[]'); } catch { state.images = []; } }
function save() { localStorage.setItem(imageKey, JSON.stringify(state.images)); updateStats(); }
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(window.__toast); window.__toast = setTimeout(() => el.classList.remove('show'), 3500); }
function updateStats() { $('#countText').textContent = state.images.length; $('#storageText').textContent = `${state.images.length} ảnh`; $('#storageBar').style.width = `${Math.min(100, state.images.length * 8)}%`; }
function showView(view) { $('#libraryView').classList.toggle('hidden', view !== 'library'); $('#settingsView').classList.toggle('hidden', view !== 'settings'); $('#pageTitle').textContent = view === 'settings' ? 'Thiết bị & nền hệ thống' : 'Không gian của bạn'; document.querySelectorAll('.nav-item').forEach((n) => n.classList.toggle('active', n.dataset.view === view)); renderGallery(); }
function renderGallery() { const gallery = $('#gallery'); const empty = $('#emptyState'); const filtered = state.images.filter((image) => state.filter === 'all' || image.kind === state.filter); gallery.innerHTML = filtered.map((image, index) => `<article class="wallpaper-card" data-id="${image.id}" style="animation-delay:${index * 45}ms"><img src="${image.dataUrl}" alt="${esc(image.name)}">${image.kind === 'gif' ? '<span class="gif-badge">GIF / FRAME</span>' : ''}<div class="card-overlay"><div><strong>${esc(image.name)}</strong><small>${image.kind === 'gif' ? 'GIF → NỀN WINDOWS' : 'ẢNH TĨNH'}</small></div><span>↗</span></div></article>`).join(''); empty.classList.toggle('hidden', filtered.length > 0); gallery.classList.toggle('hidden', filtered.length === 0); document.querySelectorAll('.wallpaper-card').forEach((card) => card.addEventListener('click', () => openDetail(card.dataset.id))); updateStats(); }
function openDetail(id) { const image = state.images.find((item) => item.id === id); if (!image) return; state.selected = image; $('#detailMedia').innerHTML = `<img src="${image.dataUrl}" alt="${esc(image.name)}">`; $('#detailName').textContent = image.name; $('#detailType').textContent = image.kind === 'gif' ? 'GIF / WINDOWS FRAME' : 'STATIC WALLPAPER'; $('#detailMeta').textContent = `${formatBytes(image.size)} · ${new Date(image.createdAt).toLocaleDateString('vi-VN')}`; $('#detailDialog').showModal(); }
function formatBytes(bytes) { return bytes ? `${(bytes / 1024 / 1024).toFixed(1)} MB` : 'Kích thước không xác định'; }
function readFile(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
async function addFiles(files) { const list = Array.from(files); for (const file of list) { if (!file.type.startsWith('image/')) continue; try { state.images.unshift({ id: crypto.randomUUID(), name: file.name, size: file.size, type: file.type, kind: file.type === 'image/gif' ? 'gif' : 'static', dataUrl: await readFile(file), createdAt: Date.now() }); } catch { toast('Không thể đọc một ảnh.'); } } save(); renderGallery(); toast(list.length > 1 ? `Đã thêm ${list.length} ảnh vào thư viện.` : 'Đã thêm ảnh vào thư viện.'); }
function fitToWallpaper(dataUrl) { return new Promise((resolve, reject) => { const image = new Image(); image.onload = () => { const width = 2560; const height = 1440; const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const scale = Math.max(width / image.naturalWidth, height / image.naturalHeight); const drawWidth = image.naturalWidth * scale; const drawHeight = image.naturalHeight * scale; const x = (width - drawWidth) / 2; const y = (height - drawHeight) / 2; const context = canvas.getContext('2d'); context.imageSmoothingEnabled = true; context.imageSmoothingQuality = 'high'; context.drawImage(image, x, y, drawWidth, drawHeight); resolve(canvas.toDataURL('image/png')); }; image.onerror = reject; image.src = dataUrl; }); }
async function wallpaperPayload(image) { return { dataUrl: await fitToWallpaper(image.dataUrl), wasGif: image.kind === 'gif' }; }
async function setWallpaper() { if (!state.selected) return; const button = $('#wallpaperBtn'); button.disabled = true; button.textContent = 'Đang xử lý…'; try { const payload = await wallpaperPayload(state.selected); const result = window.chilltheme ? await window.chilltheme.setWallpaper(payload) : { ok: false, message: 'Hãy chạy app bằng Electron để thay nền Windows.' }; toast(result.message); if (result.ok) $('#detailDialog').close(); } catch { toast('Không thể chuyển ảnh thành nền Windows.'); } button.disabled = false; button.textContent = '✦ Thay nền Windows'; }
async function setOverlayWallpaper() { if (!state.selected) return; const button = $('#overlayBtn'); button.disabled = true; button.textContent = 'Đang căn màn…'; try { const payload = await wallpaperPayload(state.selected); const result = window.chilltheme ? await window.chilltheme.setOverlayWallpaper(payload) : { ok: false, message: 'Hãy chạy app bằng Electron để đè màn.' }; toast(result.message); } catch { toast('Không thể tạo overlay theo màn hình.'); } button.disabled = false; button.textContent = '▧ Đè màn'; }
async function restoreWallpaper() { const result = window.chilltheme ? await window.chilltheme.restoreWallpaper() : { ok: false, message: 'Hãy chạy app bằng Electron để khôi phục nền.' }; toast(result.message); }
async function removeOverlayWallpaper() { const result = window.chilltheme ? await window.chilltheme.removeOverlayWallpaper() : { ok: false, message: 'Hãy chạy app bằng Electron để gỡ đè.' }; toast(result.message); }

$('#uploadBtn').addEventListener('click', () => $('#fileInput').click()); $('#emptyUpload').addEventListener('click', () => $('#fileInput').click()); $('#fileInput').addEventListener('change', (e) => addFiles(e.target.files));
$('#closeDialog').addEventListener('click', () => $('#detailDialog').close()); $('#deleteBtn').addEventListener('click', () => { if (!state.selected) return; state.images = state.images.filter((image) => image.id !== state.selected.id); save(); $('#detailDialog').close(); renderGallery(); toast('Đã xóa ảnh khỏi thư viện.'); });
$('#wallpaperBtn').addEventListener('click', setWallpaper); $('#overlayBtn').addEventListener('click', setOverlayWallpaper); $('#restoreBtn').addEventListener('click', restoreWallpaper); $('#restoreDialogBtn').addEventListener('click', restoreWallpaper); $('#removeOverlayBtn').addEventListener('click', removeOverlayWallpaper); $('#removeOverlayDialogBtn').addEventListener('click', removeOverlayWallpaper);
document.querySelectorAll('.chip').forEach((chip) => chip.addEventListener('click', () => { state.filter = chip.dataset.filter; document.querySelectorAll('.chip').forEach((c) => c.classList.toggle('active', c === chip)); renderGallery(); }));
document.querySelectorAll('.nav-item').forEach((item) => item.addEventListener('click', () => showView(item.dataset.view))); $('#searchBtn').addEventListener('click', () => toast('Tìm kiếm nâng cao sẽ có trong bản tiếp theo.'));
load(); showView('library');
